baseURL = "https://RZYN2020.github.io/journal/"
title = "Ekstasis's Journal"
theme = "yinyang"
languageCode = "zh-cn"
DefaultContentLanguage = "cn"

[params]
headTitle = "Ekstasis's Journal"

[[params.socials]]
  name = "Blog"
  link = "https://RZYN2020.github.io"

[[params.socials]]
  link = "/journal/map.html"
  name = "Travel"


mainSections = ["posts"]