baseURL = "https://RZYN2020.github.io"
title = "Ekstasis's Journal"
theme = "yinyang"
languageCode = "zh-cn"
DefaultContentLanguage = "cn"

[params]
headTitle = "Ekstasis's Journal"

[[params.socials]]
  name = "Blog"
  link = "https://RZYN2020.github.io"

[[params.socials]]
  link = "/map.html"
  name = "Travel"


[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "中文"
    weight = 1
  [languages.ja]
    contentDir = "content/ja"
    languageName = "日本語"
    weight = 2
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 3

mainSections = ["posts"]