title = "Ekstasis's Journal"
theme = "yinyang"
languageCode = "zh-cn"
DefaultContentLanguage = "cn"

[params]
headTitle = "Ekstasis's Journal"

[[params.socials]]
  name = "RSS"
  link = "/index.xml"

[[params.socials]]
  name = "Blog"
  link = "https://RZYN2020.github.io"


[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1
  [languages.ja]
    contentDir = "content/ja"
    languageName = "Japanese"
    weight = 2
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 3

mainSections = ["posts"]